### ISSUE TITLE
Question about Image Preprocessing and Handling Multiple Masks in the BUSI Dataset

### ISSUE THREAD

**Issue by Studentpengyu** [FengheTan9/CMU-Net#7]
Thank you for sharing your interesting work. I am currently implementing your model, but I'm experiencing a significant difference in performance. I suspect that the issue may lie in my image preprocessing steps.

In the BUSI dataset, some images correspond to multiple masks. My approach has been to directly combine these multiple masks into a single final mask for the image. Is this the correct method to use?

Could you please share how you handle multiple masks in your preprocessing? Thank you for your assistance!

**Comment by FengheTan9** [comment]
Thanks for focusing on our work. Since the variance of the segmentation results of the BUSI dataset is relatively large, I think the poor performance is caused by the division. You can follow our [CMUNeXt](https://github.com/FengheTan9/CMUNeXt) and use [the same split](https://github.com/FengheTan9/Medical-Image-Segmentation-Benchmarks/tree/main/data). The masks need to be merged.

**Comment by Studentpengyu** [comment]
Thank you for your prompt response!
